version: "3"
services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx/
    restart: always
    ports:
      - "443:443"
    networks:
      mynet:
        ipv4_address: "172.18.1.2"
    volumes:
      - wp:/var/www/html
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    build:
      context: ./requirements/wordpress/
    environment:
      - DBNAME=${MARIA_DBNAME}
      - DBUSER=${MARIA_USER}
      - DBPASS=${MARIA_PASSWORD}
      - DBHOST=${WP_DBHOST}
      - URL=${URL}
      - TITLE=${WP_TITLE}
      - ADMIN_USER=${WP_ADMIN_USER}
      - ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - USER=${WP_USER}
      - PASSWORD=${WP_PASSWORD}
      - EMAIL=${WP_EMAIL}
    restart: always
    ports:
      - "9000:9000"
    networks:
      mynet:
        ipv4_address: "172.18.1.3"
    volumes:
      - wp:/var/www/html
  mariadb:
    container_name: mariadb
    restart: always
    env_file:
      - .env
    build:
      context: ./requirements/mariadb
      args:
        - NEW_USER=${MARIA_USER}
        - ROOT_PASSWORD=${MARIA_ROOT_PASSWORD}
        - NEW_DB_PASSWORD=${MARIA_PASSWORD}
        - NEW_DB_NAME=${MARIA_DBNAME}
        - NEW_HOST=${MARIA_DBHOST}
    ports:
      - "3306:3306"
    networks:
      mynet:
        ipv4_address: "172.18.1.4"
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/jfrancai/data/mysql
      o: bind
  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/jfrancai/data/html
      o: bind
networks:
  mynet:
    ipam:
      driver: default
      config:
        - subnet: "172.18.1.0/24"
