version: "3"
services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    ports:
      - "443:443"
    restart: always
    networks:
      mynet:
        ipv4_address: "172.18.1.2"
    volumes:
      - wp:/var/www/html
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress/
    ports:
      - "9000:9000"
    restart: always
    networks:
      mynet:
        ipv4_address: "172.18.1.3"
    volumes:
      - wp:/var/www/html
  mariadb:
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    build:
      context: ./requirements/mariadb
      args:
        - NEW_USER=${NEW_USER}
        - ROOT_PASSWORD=${ROOT_PASSWORD}
        - NEW_DB_PASSWORD=${NEW_DB_PASSWORD}
        - NEW_DB_NAME=${NEW_DB_NAME}
        - HOST=${HOST}
    networks:
      mynet:
        ipv4_address: "172.18.1.4"
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/jfrancai/data/mysql
      o: bind
  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/jfrancai/data/html
      o: bind
networks:
  mynet:
    ipam:
      driver: default
      config:
        - subnet: "172.18.1.0/24"
