version: "3"
services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    ports:
      - "443:443"
    restart: always
    networks:
      mynet:
        ipv4_address: "172.18.1.2"
    volumes:
      - wp
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress/
    ports:
      - "9000:9000"
    restart: always
    networks:
      mynet:
        ipv4_address: "172.18.1.3"
    volumes:
      - /var/www/html:/var/www/html
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    ports:
      - "3306:3306"
    networks:
      mynet:
        ipv4_address: "172.18.1.4"
    volumes:
      - db
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/mysql
      o: bind
  wp:
    driver: local
    driver_opts:
      type: none
      device: /var/www/html
      o: bind
networks:
  mynet:
    ipam:
      driver: default
      config:
        - subnet: "172.18.1.0/24"
